rerun_ip = [192, 168, 10, 135]
years = [2020]
update_interval_seconds = 5

[logs]
en_passant_mates = false
double_disambiguation_checkmates = true
double_disambiguation_capture_checkmates = true

[output]
rare_moves = true
data = false